<a href="https://colab.research.google.com/github/Abdouramane-qr/mini_projet_data_analysis/blob/main/mini_projet_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#INSTALLATION DES BIBLIOTHEQUES

In [ ]:
!pip install pandas
!pip install numpy
!install matplotlib
!install seaborn

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)
install: missing destination file operand after 'matplotlib'
Try 'install --help' for more information.
install: missing destination file operand after 'seaborn'
Try 'install --help' for more information.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/Mini_Projet/BF/BF.txt', sep='\t', header=None, dtype=str)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,2282318,Pouéné,Pouene,NaN,9.72908,-2.7866,H,STM,BF,NaN,00,NaN,NaN,NaN,0,NaN,226,Africa/Abidjan,2023-11-07
1,2285251,Léraba Occidentale,Leraba Occidentale,"Badini,La Leraba Occidentale,Leraba,Leraba Occ...",10.28333,-5.11667,H,STM,BF,CI,00,NaN,NaN,NaN,0,NaN,283,Africa/Abidjan,2023-11-07
2,2287216,Kéléouoro,Keleouoro,"Keleouoro,Keleworo,Kéléouoro,Kéléworo",9.80748,-4.05023,H,STM,BF,"BF,CI",00,NaN,NaN,NaN,0,NaN,261,Africa/Abidjan,2023-11-07
3,2294066,White Volta,White Volta,"Nakambe,Nakambé,Nakanbe,Nakanbé,Volta Blanche,...",8.70194,-0.99056,H,STM,BF,GH,00,NaN,NaN,NaN,0,NaN,75,Africa/Accra,2023-11-08
4,2298457,Issana Bouga,Issana Bouga,"Issana Bouga,Lanyung,Lanyunga",10.91667,-1.18333,H,STM,BF,NaN,00,NaN,NaN,NaN,0,NaN,178,Africa/Accra,2023-11-08

##3.Appliquer les opérations de prétraitement et filtres nécessaires à ce fichier, pour ne garder que les colonnes correspondantes



* Identifiants et Renommage

In [ ]:
# Colonnes officielles du format Geonames
columns = [
    "geonameid", "name", "asciiname", "alternatenames", "latitude", "longitude",
    "feature_class", "feature_code", "country_code", "cc2", "admin1_code",
    "admin2_code", "admin3_code", "admin4_code", "population", "elevation",
    "dem", "timezone", "modification_date"
]

# Assigner les noms de colonnes
df.columns = columns

#Filter des colonnes necessaires
df_filtered = df[["geonameid", "name", "latitude", "longitude"]]

#Renommer les colonnes
df_filtered.columns = ["ID", "location_name", "lat", "long"]
df_filtered.head()

        ID       location_name       lat      long
0  2282318              Pouéné   9.72908   -2.7866
1  2285251  Léraba Occidentale  10.28333  -5.11667
2  2287216           Kéléouoro   9.80748  -4.05023
3  2294066         White Volta   8.70194  -0.99056
4  2298457        Issana Bouga  10.91667  -1.18333



*Sauvegarder ces données dans un fichier CSV, nommez-le burkina_location.csv

In [ ]:
df_filtered.to_csv(r'/content/drive/MyDrive/Mini_Projet/burkina_location.csv',
    index=False,
    encoding="utf-8")
df_filtered.head()

        ID       location_name       lat      long
0  2282318              Pouéné   9.72908   -2.7866
1  2285251  Léraba Occidentale  10.28333  -5.11667
2  2287216           Kéléouoro   9.80748  -4.05023
3  2294066         White Volta   8.70194  -0.99056
4  2298457        Issana Bouga  10.91667  -1.18333

##4 - Opérations sur le fichier CSV burkina_location.csv.



* extraction des données contenant le nom 'gounghin', enregistrez-le sous le fichier gounghin.csv

In [ ]:
import pandas as pd

#Chargeement du fichier
df_filtered = pd.read_csv(r'/content/drive/MyDrive/Mini_Projet/burkina_location.csv')

df_gounghin = df_filtered[df_filtered['location_name'].str.contains('gounghin', case=False, na=False)]

df_gounghin.to_csv(r'/content/drive/MyDrive/Mini_Projet/gounghin.csv', index=False)

df_gounghin.head()

             ID       location_name       lat     long
153     2353306            Gounghin  12.06677 -1.42134
7269    2360473            Gounghin  12.62488 -1.36398
10260   2570204            Gounghin  12.31436 -1.37900
10746  10342749            Gounghin  12.06667 -0.15000
10759  10629032  BICIAB // Gounghin  12.35921 -1.54273



* extraiction de la sous-partie de la base de données (fichier burkina_location.csv), dont les noms les premières lettres des noms de lieux sont compris entre 'A' et 'P' (ordre alphabétique)

In [ ]:
df_A_P = df_filtered[df_filtered['location_name'].str[0].str.upper().between('A', 'P')]

df_A_P.to_csv(r'/content/drive/MyDrive/Mini_Projet/A_P.csv', index=False)

df_A_P.head()

          ID          location_name       lat     long
0    2282318                 Pouéné   9.72908 -2.78660
1    2285251     Léraba Occidentale  10.28333 -5.11667
2    2287216              Kéléouoro   9.80748 -4.05023
4    2298457           Issana Bouga  10.91667 -1.18333
137  2353290  Forêt Classée de Ziga  12.47106 -1.08644



* Identification respectivement, la latitude, la longitude minimale et les noms de lieux correspondants

In [ ]:
min_lat = df_filtered['lat'].min()
min_lat_name = df_filtered[df_filtered['lat']==min_lat]['location_name'].tolist()

min_long = df_filtered['long'].min()
min_long_name = df_filtered[df_filtered['long']==min_long]['location_name'].tolist()

print(f"Latitude Minimale: {min_lat}")
print(f"Nom des Lieux correspondants: {', '.join(min_lat_name)}")

print(f"Longitude Minimale: {min_long}")
print(f"Nom des Lieux correspondants: {', '.join(min_long_name)}")

Latitude Minimale: 5.21609
Nom des Lieux correspondants: Komoé
Longitude Minimale: -5.65968
Nom des Lieux correspondants: Banifing



*  les lieux dont les coordonnées sont comprises entre (lat >= 11 et lon <= 0.5)

In [ ]:
df_coord= df_filtered[(df_filtered['lat']>=11) & (df_filtered['long']<=0.5)]
df_coord.to_csv(r'/content/drive/MyDrive/Mini_Projet/coord.csv', index=False)


print("Lieux avec lat >= 11 et lon <= 0.5 :\n", df_coord["location_name"].tolist())

df_coord.head()

Lieux avec lat >= 11 et lon <= 0.5 :

        ID location_name       lat     long
5  2353158      Zyonguen  12.36667 -0.45000
6  2353159     Zyiliwèlè  12.38333 -2.73333
7  2353160        Zyanko  12.78333 -0.41667
8  2353161         Zouta  13.14908 -1.28197
9  2353162     Zourtenga  12.95741 -1.28745

## 5 - Sorties Excel



*   Création d'un fichier Excel et nommination: mini_projet

In [ ]:
with pd.ExcelWriter("/content/drive/MyDrive/Mini_Projet/mini_projet.xlsx") as writer:
  df_gounghin.to_excel(writer, sheet_name="gounghin", index=False)
  df_A_P.to_excel(writer, sheet_name="A_P", index=False)


print("Fichier 'mini_projet.xlsx' créé avec succès.")

Fichier 'mini_projet.xlsx' créé avec succès.